### ISSUE TITLE
Get info about loaded Native ad

### ISSUE THREAD

**Issue by Zozulinsky** [AppLovin/AppLovin-MAX-SDK-Android#113]
Hello! How do I get the info on the screenshot inside the onNativeAdLoaded method (advertiser, body, title, CTA)?
<img width="594" alt="Снимок экрана 2022-01-25 в 17 52 06" src="https://user-images.githubusercontent.com/13776823/151001087-797757a5-529b-4865-8e79-ed7ecbfa7ec3.png">

**Comment by chauduyphanvu** [comment]
@Zozulinsky, the callback's signature is:

```java
public void onNativeAdLoaded(final MaxNativeAdView nativeAdView, final MaxAd ad)
```

You can use the `nativeAdView` param and get those assets by calling the corresponding getter (e.g. `nativeAdView.getBodyTextView()`). Since the return type is a `View`, you will then need to extract the View's content (e.g. `TextView.getText().toString()`).

Vu Chau
AppLovin Team

**Comment by Zozulinsky** [comment]
@chauduyphanvu thanks!
