### ISSUE TITLE
Account disabled - Support is dead!!!

### ISSUE THREAD

**Issue by ghost** [AppLovin/AppLovin-MAX-SDK-Android#163]
This account is currently disabled. If you've recently signed up, we will be in touch shortly. If you believe you are getting this email as an error, please contact [support@applovin.com]. I just woke up to find this and also I got this email. 

The following invoices were fully paid by credit that we previously received from you. Therefore, no payment will be sent to you for those bills.

What is going on with Applovin????? Support is nonexistent and my account is kind of fucked up right now and nobody is giving me any answers. I never got an email about my account being disabled or anything like that. Can somebody get in touch with me ASAP?

**Comment by NanaAmoah** [comment]
Hi @kovachx, could you please share your account email ID ?

**Comment by kovachx** [comment]
viktorgeokov@googlemail.com

**Comment by NanaAmoah** [comment]
Thanks for sharing the account email ID. Could you send an email to publisher_support@applovin.com ? Someone from our business development team will be in touch.

**Comment by kovachx** [comment]
That email doesnt exist. Could you forward this somehow I am worried dont know whats going on with account.

**Comment by NanaAmoah** [comment]
Hi @kovachx, I've forwarded your issue to the correct partner support email address.

**Comment by kovachx** [comment]
I contacted them 3 days ago and even now with your help they still haven't contacted me for some reason. Really unprofessional.

**Comment by winnerawan** [comment]
my account got disabled too for no reason

**Comment by thomasmso** [comment]
@winnerawan - Could you send an email to [publisher_support@applovin.com](mailto:publisher_support@applovin.com) ? Someone from our business development team will be in touch.

**Comment by Maradox** [comment]
@NanaAmoah Our account was disabled as well. Could you please provide the email address which you used when you forwarded the issue for kovachx?

**Comment by leopardie** [comment]
@thomasmso hello, our account (gamecaff @ gmail.com ) was also disabled for no reason. We have contacted your support team and BD team, and no response from your support team, and no privilege from your BD team.  This significantly affected our game's performance because our game cannot show ADs not just for Applovin, but for all other ADs like Admob, pangle, unity, vungle, Ironsource, etcs. I hope we could receive a response or explanation why we cannot use both Applovin and Max at the same time because of your system's error.

**Comment by thomasmso** [comment]
@Maradox / @leopardie - Please use the email I provided above. GitHub should be reserved for technical issues, our engineering team has no control over account reinstatements.

**Comment by leopardie** [comment]
@thomasmso ok. Thanks issues solved. Apart from technical issues, there are some suggestions for your team.

1.	When your system suspends or disables an Applovin account, the prompt words are not inappropriate. It simply says, password is invalid, which is definitely misleading. When I try changing the password, I got informed that “This account is currently disabled. If you've recently signed up, we will be in touch shortly. If you believe you are getting this email as an error, please contact [support@applovin.com].”
This series of tips were misleading users. 

2.	When my Applovin account was disabled, my Max mediation was accordingly disabled too, which caused our game instantly disfunction and all other platform Ads like Admob, UnityADs, Ironsource, Vungle,Pangle unable to show ADs. As a result, a lot of players went to leave their 1 star review on GooglePlay, saying our game exists to deceiving players and all ads couldn’t play at all.

3, Even though your system or your team thought our app’s traffic were involved in fraud. It it is necessary to provide appropriate procedure and instructions to appeal and explain. Also when an app were involved in fraud, there is no need to disable all Max's functions. For instance, when a Google Play developer's app was violating policy, Google won't prevent the user to access his or her email and youtube.

4, Even my account were restored, but there are no support and no followup regarding this issue. It is weird that I was still believed to forget our passwords.
5, Every company has its own company culture, and it is generally accepted for users that an accounts is disabled. After all, it is the era of AI robot. Human beings always make mistakes, let alone AI robot. But It is a good practice for your company to send “Normal disable Email instead of misleading users with invalid passwords, providing appeal process and progress.

Finally, Max is a great tool and I hope your team makes more great products.

**Comment by yahya774** [comment]
Hi, please i have some probleme my account has disabled, what th solution??
Email: Yahiabouhou@gmail.com

**Comment by yahya774** [comment]
@NanaAmoah Hi, please i have some probleme my account has disabled, what th solution??
Email: [Yahiabouhou@gmail.com](mailto:Yahiabouhou@gmail.com)

**Comment by adriyaalifa1** [comment]
Hi, please i have some probleme my account has disabled, what th solution??

**Comment by adriyaalifa1** [comment]
Hi, please i have some probleme my account has disabled, what th solution??
my email=  adriyaalifa1@gmail.com

**Comment by iOSqlv** [comment]
Hello,
Our account also has the same problem.
Please try to check and help us recover your account.
Our mail id: dovanhoang.inc@gmail.com
Thanks.

**Comment by EraldoCog** [comment]
my account was also suspended on 24-06-2024 and so far I have not been able to resolve this because the support leaves a lot to be desired, I am not receiving the amounts that my app generated and I am also not generating any revenue oois everything was managed by applovin and So far no one has answered me how can I solve it?

**Comment by HakanYksl** [comment]
Hi @thomasmso We are having a similiar issue, After we integrate Admob and Unity we got suspended next day.

**Comment by mayankbhoriaDecision** [comment]
Hi @ leopardie Can you please help me as i my account was also suspended without any reason? Can you provide any contact details for an applovin support person?

**Comment by mayankbhoriaDecision** [comment]
Hi @leopardie  Can you please help me as i my account was also suspended without any reason? Can you provide any contact details for an applovin support person?

**Comment by mayankbhoriaDecision** [comment]
@thomasmso  Hi Can you please help me as i my account was also suspended without any reason? Can you provide any contact details for an applovin support person?
