### ISSUE TITLE
No impressions with facebook native 

### ISSUE THREAD

**Issue by abdrrahim122** [AppLovin/AppLovin-MAX-SDK-Android#186]
Hello,

I have integrated two native ads format on my application but I don't get any impression. The ad requests are there but there is no impressions.

![image](https://user-images.githubusercontent.com/6411579/154863657-d425e326-334a-4b6e-b549-f5bdf57db900.png)

The picture is from Facebook console, in Max console I can see nothing.

Is an Android application and I'm using the last version of Applovin SDK(11.1.2) and also de last version of the facebook adapter(6.8.0.11)

Is this a known problem?

Thank you!

**Comment by chauduyphanvu** [comment]
@abdrrahim122, since your Meta dashboard is showing some bid responses (~76% bid rate) and a very high win rate (93-96%), I'd say all is well from Meta's end. The fact that there are no impressions might mean 1) you never show your loaded ads (which is unlikely), or 2) some ad assets might be missing and so Meta won't track an impression. 

Have you confirmed via test mode whether you can successfully request and show native ads from Meta? That'd be a good check for this type of issue. Look for the log `Native shown` - that is an indication that [Meta has tracked an impression](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/blob/master/Facebook/src/main/java/com/applovin/mediation/adapters/FacebookMediationAdapter.java#L1165-L1170). 

Vu Chau
AppLovin Team

**Comment by abdrrahim122** [comment]
@chauduyphanvu yes, I confirmed with the test mode and the Natvie Ad is successfully shown.

![image](https://user-images.githubusercontent.com/6411579/155373040-fb896b5f-5afd-482a-a8af-3adc02d1522d.png)


Also in the logs I can get the Native shown log:
![Screenshot_2](https://user-images.githubusercontent.com/6411579/155374392-856853a2-9feb-465f-933a-163297f5d2eb.png)

**Comment by chauduyphanvu** [comment]
That looks good - thanks for the confirmation! This looks like an issue only in production (live ads) then (your SDK/adapter integration is fine).

Because we only track impressions after Meta has fired their `onLoggingImpression()` callback, this seems to be more of an issue with Meta's SDK (i.e. they aren't tracking it, so we also aren't tracking it, so you see no data on both dashboards). Do you have someone on Meta's side that you can escalate this issue to?

**Comment by abdrrahim122** [comment]
@chauduyphanvu No, I don't have someone from Meta, actually we are migrating our applications from mopub to applovin and the mopub native Ad is still working correctly at the moment.

**Comment by Apsaliya** [comment]
I'm also facing this issue. I can see impressions from Meta native bidding in MAX dashboard but Meta dashboard does not show anything. This problem is only with Meta Native banner ads. Other types impressions are correctly being logged (both on Meta and MAX dashboard

MAX dashboard:
<img width="1361" alt="Screenshot 2022-02-25 at 5 46 10 PM" src="https://user-images.githubusercontent.com/14962707/155714839-21cfacc1-3b7b-4ed4-8176-78230f2a3990.png">


Meta dashboard:
<img width="1210" alt="Screenshot 2022-02-25 at 5 49 28 PM" src="https://user-images.githubusercontent.com/14962707/155714849-21ce4d3e-6cfc-4253-9211-16d11c264943.png">
)

**Comment by abdrrahim122** [comment]
@Apsaliya and for the Native Ad, does it work for you?

Is the unit Ad id you have the problem with is a unit Ad id you just created?
because I think if I put an old unit ad id, it works but the new ones don't work, but I'm not sure about that I'll need more data to confirm

**Comment by Apsaliya** [comment]
I'm using Meta's native banner placement.  Till recently they were not supported but recent version update of MAX sdk and Meta adapter started supporting it. However after integration, It shows impressions on Max dashboard but not on Meta dashboard.

**Comment by maxakash** [comment]
> @Apsaliya - I recommend checking the simple exercise from my earlier response to validate your integration: [#186 (comment)](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/issues/186#issuecomment-1048981569). Basically, if that works for you then we can be sure that Meta is tracking impressions.
> 
> If, for some reasons, impressions aren't shown on the Meta dashboard then it we might need to find a way to let the Meta team know.

I am using native banner ads from Meta and my impressions are correctly tracked.

One of the main reasons for above people might be they are using native ad units instead of native banner ad units from Meta and selecting native banner option in MAX.

**Comment by abdrrahim122** [comment]
@chauduyphanvu @maxakash 
If I use the applovin native Ad with small template, what is the type of meta ad unit I have to put?
is meta native Ad or meta native banner ad?
![image](https://user-images.githubusercontent.com/6411579/156221185-f2737dc5-8254-44d4-a250-acfd487f4dbf.png)

**Comment by chauduyphanvu** [comment]
@abdrrahim122, either one will work. It's up to your preference.

**Comment by abdrrahim122** [comment]
@chauduyphanvu is there a way to test the small template?
Currently even if I select small templete in test mode I get the medium template

**Comment by abdrrahim122** [comment]
@chauduyphanvu no is not working for me, even if i use small template I get always the medium and some assets are not showing for meta and applovin also (and I think this is the reason why I get no impression on facebook/applovin)

![image](https://user-images.githubusercontent.com/6411579/156622669-2176a105-cafb-4a62-9b7a-3b61fa2cbf6c.png)

![image](https://user-images.githubusercontent.com/6411579/156622693-4f190803-ff16-46a7-97f3-c790b8426cfc.png)

**Comment by chauduyphanvu** [comment]
@abdrrahim122 - let us investigate this and get back to you. Stay tuned!

**Comment by chauduyphanvu** [comment]
@abdrrahim122 - could you check again to see if the issue persists? If it does, could you share your native ad implementation code?

**Comment by abdrrahim122** [comment]
@chauduyphanvu I still get the same issue

My implementation:
`    public void initApplovinMaxNativeAds(NativeAdScreen nativeAdScreen){

        MaxNativeAdLoader nativeAdLoader;
        final MaxAd[] nativeAd = {null};

        String adUnit = context.getString(R.string.applovin_medium_native_ad_id);
        int id = R.id.applovin_ad_view_container;
        if(nativeAdScreen.equals(NativeAdScreen.SMALL_NATIVE)){
            adUnit = context.getString(R.string.applovin_small_native_ad_id);
            id =  R.id.applovin_ad_view_container_small;
        }

        FrameLayout nativeAdContainer = ((Activity) context).findViewById(id);

        if(nativeAdContainer==null) return;

        nativeAdLoader = new MaxNativeAdLoader( adUnit, (Activity) context);

        nativeAdLoader.setNativeAdListener( new MaxNativeAdListener(){
            @Override
            public void onNativeAdLoaded(final MaxNativeAdView nativeAdView, final MaxAd ad){
                // Clean up any pre-existing native ad to prevent memory leaks.
                if (nativeAd[0] != null )
                {
                    nativeAdLoader.destroy(nativeAd[0]);
                }

                // Save ad for cleanup.
                nativeAd[0] = ad;

                if(nativeAdContainer==null) return;
                // Add ad view to view.
                destoyFacebookNativeAds(nativeAdScreen);
                nativeAdView.setBackgroundColor(context.getResources().getColor(SongDetailsActivity.colors[SongDetailsActivity.trackColor]));
                nativeAdView.getAdvertiserTextView().setTextColor(Color.WHITE);
                nativeAdView.getBodyTextView().setTextColor(Color.WHITE);
                nativeAdView.getIconImageView().setBackgroundColor(Color.WHITE);
                nativeAdView.getTitleTextView().setTextColor(Color.WHITE);
                nativeAdView.getCallToActionButton().setTextColor(Color.WHITE);
                nativeAdView.getIconContentView().setBackgroundColor(Color.WHITE);

                nativeAdContainer.removeAllViews();
                nativeAdContainer.addView( nativeAdView );
                nativeAdContainer.setVisibility(View.VISIBLE);
                nativeRetryAttempt = 0;
            }

            @Override
            public void onNativeAdLoadFailed(final String adUnitId, final MaxError error){
                // We recommend retrying with exponentially higher delays up to a maximum delay
                Log.d("onNativeFail", "APPLOVIN native fail: "+error);
                nativeRetryAttempt++;
                if(nativeRetryAttempt<=5){
                    initNativeAds(nativeAdScreen, false);
                }
            }

            @Override
            public void onNativeAdClicked(final MaxAd ad)
            {
                // Optional click callback
            }
        } );

        nativeAdLoader.loadAd();
    }`

`    <androidx.appcompat.widget.LinearLayoutCompat
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="20dp"
        android:padding="10dp"
        android:orientation="horizontal"
        android:gravity="center">
        <FrameLayout
            android:id="@+id/applovin_ad_view_container_small"
            android:layout_width="match_parent"
            android:layout_height="150dp"
            android:orientation="vertical"
            android:visibility="gone"
            >
        </FrameLayout>
    </androidx.appcompat.widget.LinearLayoutCompat>`


![image](https://user-images.githubusercontent.com/6411579/157324790-ce636d1a-ae64-45ec-a89e-dbbdb110a46f.png)

**Comment by abdrrahim122** [comment]
@chauduyphanvu 
Is there a way to force using small template from the code?
Is there a log can I check to know what template size I receive from the server -side?

**Comment by chauduyphanvu** [comment]
@abdrrahim122 - you cannot force a template size change from code because doing so can't update the ad unit on the MAX dashboard. Alternatively, you could create 2 ad unit IDs—one for each template size, and request the appropriate one.

To know which template size you are requesting / getting served, check for the `template` key in the verbose log. For example, `"template":"medium_template_1"` refers to the medium template, and `"template":"small_template_1"` refers to the small template.

**Comment by abdrrahim122** [comment]
@chauduyphanvu that's exactly what I suspected I get the medium template event if the small template is chosen.

![image](https://user-images.githubusercontent.com/6411579/158237638-c7f2357b-ac5b-4c9b-876c-f07f9bf8c15f.png)

**Comment by santoshbagadi** [comment]
Hi @abdrrahim122 , It looks like you have test mode enabled. Right now, only medium template is supported in test mode. We are working on adding support for all template types in test mode, but for now you can try disabling test mode to load small template ads.

**Comment by santoshbagadi** [comment]
This should now be fixed for test mode. Please note that a valid ad unit ID is required.
