### ISSUE TITLE
How to show the same native ad with a different container view repeatedly ?

### ISSUE THREAD

**Issue by pratik-pattanaik** [AppLovin/AppLovin-MAX-SDK-Android#250]
I need to show the same native ad (loaded once) in an AlertDialog every time the dialog is opened. How do I do this ? Should I call `MaxNativeAdView.removeAllViews()` each time the dialog closes and create a new `MaxNativeAdView` each time I have to show the ad ?

**Comment by santoshbagadi** [comment]
Hi @pratik-pattanaik , You can do this multiple different ways. You can cache the loaded ad view and show it each time the dialog is opened or you can load and render the ad separately. Instead of passing in a `MaxNativeAdView` at ad load time, you can load the ad using `MaxNativeAdLoader.loadAd()` and then render it separately using `MaxNativeAdLoader.render( MaxNativeAdView, MaxAd )`. You can just cache the `MaxAd` returned and then render it whenever you need it again. 

You can check out our demo app implementation for late binding here: https://github.com/AppLovin/AppLovin-MAX-SDK-Android/blob/master/AppLovin%20MAX%20Demo%20App%20-%20Java/app/src/main/java/com/applovin/enterprise/apps/demoapp/ads/max/nativead/ManualNativeLateBindingAdActivity.java

**Comment by santoshbagadi** [comment]
This should be fixed in our latest SDK v11.3.0. Could you please update to this version and see if you still see this issue happening.

**Comment by pratik-pattanaik** [comment]
Hi ! It seems like the issue is fixed in v11.3.0 as I haven't seen an instance of this error yet in production. I needed to know one more thing. Do mediated networks need to be initialized before Applovin is ? I didn't find such an instruction in the Applovin documentation, but it was there in the Mopub documentation.

**Comment by joeapplovin** [comment]
> Do mediated networks need to be initialized before Applovin is ? I didn't find such an instruction in the Applovin documentation, but it was there in the Mopub documentation.

We handle initialization for you, so all you need to do is [initialize the AppLovin SDK](https://dash.applovin.com/documentation/mediation/android/getting-started/integration#initialize-the-sdk).

**Comment by pratik-pattanaik** [comment]
Thanks for confirming. Can you please also tell me the difference between Applovin Exchange and Applovin Bidding that I see in my Dashboard ?

**Comment by chauduyphanvu** [comment]
@pratik-pattanaik, the AppLovin Network is our first party demand and primarily UA campaigns. The AppLovin Exchange (formerly MoPub Marketplace) is our real time bidding exchange with over 100 DSPs running advertising campaigns.

**Comment by pratik-pattanaik** [comment]
I'm seeing the highest proportion of impressions (>95%) coming from Applovin exchange which is way too different from what I see in Mopub. Does the first ad bid after app installation get communicated to all mediated networks unlike in Mopub where the mediated network details aren't cached during first bid and therefore not included ?

**Comment by thomasmso** [comment]
@pratik-pattanaik - Please feel free to check out our [docs](https://dash.applovin.com/documentation/mediation/auctions/sdk-bidders) on how our auctions work. Thanks!
