### ISSUE TITLE
Interstitial Ads not properly displayed

### ISSUE THREAD

**Issue by HarshaliSachani** [AppLovin/AppLovin-MAX-SDK-Android#282]
![Applovin_InterstitialAds](https://user-images.githubusercontent.com/84327237/160456918-0957707d-d9fe-4669-94c8-d711e639c922.jpeg)
Case 1: Sometimes interstitial ads content is missing with live ads ID
Case 2: It displayed a black screen for some period of time after that ads displayed

**Comment by chauduyphanvu** [comment]
@HarshaliSachani, how often is this happening to you? If you're able to reproduce it yourself, could you help share with us the [verbose log](https://dash.applovin.com/documentation/mediation/android/getting-started/advanced-settings#enable-verbose-logging) so that we can take a deeper look? 

Thank you.

**Comment by HarshaliSachani** [comment]
@chauduyphanvu It's randomly happened with live ads.
