### ISSUE TITLE
Could add a back button in mediation debugger UI

### ISSUE THREAD

**Issue by fableyjg** [AppLovin/AppLovin-MAX-SDK-Android#45]
Hi，when we update SDK, we want test differrent network ad.
In mediation debugger, it is very convenient to test ad. 
 
But， there is a question, when test network A, if I want test network B, we can only close the application，and restart again.
Could add a back button in the UI, Thank you.

**Comment by thomasmso** [comment]
Thanks for reporting this - we assume publishers will have access to devices with a physical back button, but will take your input and add a back button in a future SDK release.

**Comment by fableyjg** [comment]
> Thanks for reporting this - we assume publishers will have access to devices with a physical back button, but will take your input and add a back button in a future SDK release.

Thanks you.  In some device, physical back button was removed by the phone manufacturer.

**Comment by uchitel** [comment]
Hi @fableyjg,

We are trying to reproduce the issue. Could you please provide additional information to help us get to the root cause of the problem? Like
- Is it 100% reproducible for you?
- Does it happen when you test some particular network adapter?
- Is it device/manufacturer specific or you can reproduce it on any device with software navigation bar?
- Android version, target SDK version...
- Steps to reproduce or anything else that might be helpful

Thank you very much for your help!
