### ISSUE TITLE
interstitial ad disappears when the game is switched to the background and then back to the foreground

### ISSUE THREAD

**Issue by wang-er-s** [AppLovin/AppLovin-MAX-SDK-Android#542]
### MAX SDK Version

11.11.3

### Device/Platform Info

any android device

### Current Behavior

When integrating AppLovin MAX ads on Android, the interstitial ad disappears when the game is switched to the background and then back to the foreground. This issue occurs regardless of whether you're using Cocos Creator or Unity. Is there any solution to this problem?

### How to Reproduce

Access according to the document

**Comment by Str4tos** [comment]
Hello, I know the reason but don't know the solution. 
This occurs because game engines use the `<activity android:launchMode="singleTask">` tag for the MAIN Activity, causing a documented behavior in the Android OS. When restoring the application by tapping on the icon, all activities (including ads) above the MAIN activity in the task are destroyed. Simultaneously, activities are not destroyed when the application is restored from the list of running processes.
