### ISSUE TITLE
onAdLoadFailed callback not called

### ISSUE THREAD

**Issue by ArturRuZ** [AppLovin/AppLovin-MAX-SDK-Android#546]
### MAX SDK Version

11.11.3

### Device/Platform Info

Android

### Current Behavior

Good day!
In cases:
1. Usage of wrong package name id
2. Usage of wrong Ad unit id
3. Loading the ad, when ad is showing or when the ad is loading

There are only console-log messages about error but onAdLoadFailed callback isn't called. 
console-log messages:
1.  - (There is no error message in this case)
2. Please double-check the ad unit YOUR_AD_UNIT_ID for REWARDED
3. [MaxRewardedAd] Can not load another ad while the ad is showing or [MaxRewardedAd] An ad is already loading

### Expected Behavior

After error messages in console-log, onAdLoadFailed callback is called with error. 

### How to Reproduce

1. Use wrong package name different from applovin-MAX account
2. Use wrong ad unit id different from applovin-MAX account
3. Load rewarded ad when the ad is showing 
4. Load rewarded ad when the ad is downloading

**Comment by alvarshahanji** [comment]
@ArturRuZ this is expected behavior.

We log the error, "Invalid Request" when you use an incorrect ad unit/package name so you can update to use the correct ones.

Similarly, we log errors([AppLovinSdk] ERROR [MAInterstitialAd] Can not load another ad while the ad is showing
) when you make an ad request in an incorrect state(while the ad is loading or showing).

These errors should help you integrate correctly.
