### ISSUE TITLE
Rewarded Video methods are removed in the latest SDK 13.0

### ISSUE THREAD

**Issue by mateusz-nawrot** [AppLovin/AppLovin-MAX-SDK-Android#712]
### MAX SDK Version

13.0.0

### Device/Platform Info

N/A

### Current Behavior

Until version 12.6.1 the `MaxRewardedAdListener` had dedicated methods for rewarded videos : 
```
void onRewardedVideoStarted(@NonNull MaxAd var1);
void onRewardedVideoCompleted(@NonNull MaxAd var1);
```
The methods got deprecated in recent versions of the SDK and completely removed with version 13.0.0. 
How should one replace the usages of the old methods using the latest SDK? There seems to be no information on how to tackle this.

### How to Reproduce

Update SDK to 13.0, observe methods gone.

### Reproducible in the demo app?

Yes

**Comment by NanaAmoah** [comment]
Hi @mateusz-nawrot these APIs have been deprecated for a while because not all adapters support these callbacks. We removed them starting from AppLovin SDK 13.0.0. 

Please use our `onAdDisplayed` and `onAdHidden` [callbacks](https://developers.applovin.com/en/max/android/ad-formats/rewarded-ads#loading-a-rewarded-ad) to be notified when an ad is displayed and hidden.
