### ISSUE TITLE
The type initializer for 'MaxSdkAndroid' threw an exception.

### ISSUE THREAD

**Issue by blairwang** [AppLovin/AppLovin-MAX-SDK-Android#737]
### MAX SDK Version

13.0.0

### Device/Platform Info

any android devices

### Current Behavior

We use Unity to build the game.
On the 24th, everything was fine. However, today, the 28th, the issue occurred during packing and it happens every time.
I noticed that version 13.0.1 was released on the 27th(yesterday). Could this release have affected version 13.0.0?

In mainTemplate.gradle, here it is:

implementation 'com.applovin:applovin-sdk:+'

### Expected Behavior

no errors.

### How to Reproduce

Build the game the same way as before.

### Reproducible in the demo app?

Not Tested

**Comment by alvarshahanji** [comment]
Could you try if the issue is reproducible in our [Unity demo app](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/tree/master/DemoApp)? Could you share exact steps to reproduce if it is reproducible on the demo app?

Alternatively, could you share a sample project with exact steps to reproduce?

**Comment by blairwang** [comment]
I fixed it by doing this.
 // implementation 'com.applovin:applovin-sdk:+'

The Unity plugin has already generated [implementation 'com.applovin:applovin-sdk:13.0.0'] in mainTemplate.gradle, which conflicts with the content expanded [implementation 'com.applovin:applovin-sdk:13.0.1']  in this line.

Sorry to bother.
