### ISSUE TITLE
Consent dialog shown with showConsentDialog is very game specific

### ISSUE THREAD

**Issue by drishit96** [AppLovin/AppLovin-MAX-SDK-Android#91]
I am integrating the AppLovin android sdk and noticed that the consent dialog shown to the user mentions words like 'gameplay' and 'playing our game'.
![Screenshot_20220116-131332](https://user-images.githubusercontent.com/13049630/149651915-7c6ad164-9fd5-4438-851d-b0b120822b35.png)

The problem is that my app is not at all a game and is more of a productivity tool.
Please change the message of the consent dialog to be more generic so that it caters to both apps and games.
Thanks.

**Comment by ihassanali259** [comment]
Does it serve ads without showing consent dialog?

**Comment by drishit96** [comment]
Not sure about that, but in my code I check for consent first and once I have the consent I call loadAd on the adview.

**Comment by thomasmso** [comment]
@drishit96 - I'll work with product team on updating the copy to be non-gaming specific and update you on ETA. 
@ihassanali259 - It depends, there are some mediated networks that are not eligible in GDPR regions if a user has not explicitly consented.

**Comment by thomasmso** [comment]
@drishit96 - We're going to revamp the whole flow in Q2. Not looking to make any changes for now. Will keep thread posted on updates.

**Comment by talklittle** [comment]
Looking forward to the revamped consent flow. Hopefully that means taking on the MoPub flow which worked flawlessly, was self explanatory, and never resulted in user complaints.

The current AppLovin SDK consent dialog (v11.3.1) is getting complaints and confusion from users. First, it should be reworded with a professional tone and to not mention games. Users have expressed concern over what data is being collected, and the unprofessional tone of writing combined with the popup feels almost like a fake malware ad.

Secondly, the default behavior of dismissing the dialog should be more in line with what a user expects; maybe to deny consent. Otherwise the app will end up showing the dialog again and again when the user thinks they had already dismissed it (with the phone's Back button).  
An alternative would be to disable closing it with the Back button, and compensate by changing the flow to be much simpler and faster to set a preference (a big "Opt out" button?).
